version: 2
jobs:
  build:
    docker:
      - image: golang:1.6.4
    working_directory: /go/src/github.com/circleci/Test101
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose   
      
      #spin up and test container
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d
            docker run --network container:test101_app_1 \
              appropriate/curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:8080

      # build and push Docker image
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            TAG=latest
          else
            TAG=0.1.$CIRCLE_BUILD_NUM
          fi
          docker build -t wesleycharlesblake/test101:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push wesleycharlesblake/test101:$TAG
      

      # Deploy production
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ];
              then /bin/bash deploy.sh ;
            fi